name: dudv_base
description: Model–view–presenter (MVP) is a derivation of the model–view–controller (MVC) architectural pattern, and is used mostly for building user interfaces.
version: 1.3.0+1
homepage: https://github.com/beheobong/dudv_base

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^10.4.3
  fluttertoast: ^8.2.2
  logger: ^1.4.0

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  analyzer: ^5.13.0


assets:
    - assets/icons_ios/
  
