name: dudv_base
description: Model–view–presenter (MVP) is a derivation of the model–view–controller (MVC) architectural pattern, and is used mostly for building user interfaces.
version: 1.1.9+19
homepage: https://github.com/beheobong/dudv_base

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^10.2.0
  fluttertoast: ^8.1.2
  logger: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  analyzer: ^5.2.0


assets:
    - assets/icons_ios/`
  
