name: dudv_base
description: Model–view–presenter (MVP) is a derivation of the model–view–controller (MVC) architectural pattern, and is used mostly for building user interfaces.
version: 1.3.0+3
homepage: https://github.com/beheobong/dudv_base

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.0.1
  fluttertoast: ^8.2.4
  logger: ^2.0.2+1

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  analyzer: ^6.2.0


assets:
    - assets/icons_ios/
  
